version: '3'
services:
  webapp:
    image: pathwaycommons/factoid:${FACTOID_IMAGE_TAG:-unstable}
    depends_on:
      - db
      - grounding
    ports:
      - "${FACTOID_PORT:-3000}:3000"
    environment:
      USE_PC_GROUNDING_SEARCH:
      DB_USER:
      DB_PASS:
      DB_CERT:
      DB_HOST: "db"
      GROUNDING_SEARCH_BASE_URL: "http://grounding:3000"
  grounding:
    image: pathwaycommons/grounding-search:${GROUNDING_SEARCH_IMAGE_TAG:-latest}
    depends_on:
      - elastic
    environment:
      ELASTICSEARCH_HOST: "elastic:9200"
  indexer:
    image: pathwaycommons/grounding-search:${GROUNDING_SEARCH_IMAGE_TAG:-latest}
    depends_on:
      - elastic
    environment:
      ELASTICSEARCH_HOST: "elastic:9200"
    command: ["./wait-for-elasticsearch.sh", "elastic:9200", "npm", "run", "update"]
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
  db:
    image: rethinkdb:2.3.6
    ports:
      - "${DB_ADMIN_PORT:-8080}:8080"
    volumes:
      - dbdata:/data

volumes:
  dbdata:
  esdata: