version: "3.8"
services:
  proxy:
    image: nginx:${NGINX_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: proxy
    depends_on:
      - webapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./templates:/etc/nginx/templates
      - appdata:/var/www/app:ro
      - webroot:/var/www/html
      - certbotetc:/etc/letsencrypt
      - certbotvar:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    environment:
      NGINX_HOST:
      NGINX_PROXY_SERVER: "webapp:3000"
      STATIC_ROOT: /var/www/app/build
      IMAGE_ROOT: /var/www/app/src/styles
    networks:
      - biofactoid-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbotetc:/etc/letsencrypt
      - certbotvar:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - proxy
    command: ["certonly", "--webroot", "--webroot-path=/var/www/html", "--email", "${APP_EMAIL}", "--agree-tos", "--no-eff-email", "--force-renewal", "-d", "${NGINX_HOST}", "-d", "www.${NGINX_HOST}"]
  webapp:
    image: pathwaycommons/factoid:${FACTOID_IMAGE_TAG:-latest}
    restart: on-failure
    container_name: webapp
    depends_on:
      - db
      - grounding
      - converter
    ports:
      - "${FACTOID_PORT:-3000}:3000"
    volumes:
      - appdata:/home/appuser/app
    environment:
      BASE_URL:
      GROUNDING_SEARCH_BASE_URL: "http://grounding:3000"
      BIOPAX_CONVERTER_URL: "http://converter:8080/convert/v2/"
      SEMANTIC_SEARCH_BASE_URL:
      DB_HOST: "db"
      API_KEY:
      EMAIL_ENABLED:
      SMTP_HOST:
      SMTP_USER:
      SMTP_PASSWORD:
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_ACCESS_TOKEN_KEY:
      TWITTER_ACCESS_TOKEN_SECRET:
      TWITTER_ACCOUNT_NAME:
      NCBI_EUTILS_API_KEY:
      NODE_OPTIONS:
      EMAIL_RELPPRS_CONTACT:
      CRON_SCHEDULE:
    networks:
      - biofactoid-network
  grounding:
    image: pathwaycommons/grounding-search:${GROUNDING_SEARCH_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: grounding
    ports:
      - "${GROUNDING_PORT:-3011}:3000"
    depends_on:
      - index
    environment:
      ELASTICSEARCH_HOST: "index:9200"
      NCBI_EUTILS_API_KEY:
      ZENODO_ACCESS_TOKEN:
      ZENODO_BASE_URL:
      ZENODO_BUCKET_ID:
    networks:
      - biofactoid-network
    command: ["./wait-for-elasticsearch.sh", "index:9200", "npm", "run", "start"]
  index:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    restart: unless-stopped
    container_name: index
    volumes:
      - indata:/usr/share/elasticsearch/data
    networks:
      - biofactoid-network
  db:
    image: pathwaycommons/rethinkdb-docker:${RETHINKDB_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: db
    ports:
      - "${DB_ADMIN_PORT:-8080}:8080"
    volumes:
      - dbdata:/data
    networks:
      - biofactoid-network
  converter:
    image: pathwaycommons/factoid-converters:${FACTOID_CONVERTERS_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: converters_container
    ports:
      - "${CONVERTER_PORT:-3082}:8080"
    networks:
      - biofactoid-network

volumes:
  webroot:
  certbotetc:
  certbotvar:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/baderlab/biofactoid.org/dhparam/
      o: bind
  appdata:
  dbdata:
  indata:

networks:
  biofactoid-network:
    driver: bridge
