version: "3.4"
services:
  webapp:
    image: pathwaycommons/factoid:${FACTOID_IMAGE_TAG:-unstable}
    container_name: webapp_container
    depends_on:
      - db
      - grounding
    ports:
      - "${FACTOID_PORT:-3000}:3000"
    environment:
      BASE_URL:
      GROUNDING_SEARCH_BASE_URL: "http://grounding:3000"
      INDRA_INTERACTION_BASE_URL: "http://indra:8000/"
      DB_HOST: "db"
      API_KEY:
      EMAIL_ENABLED:
      SMTP_HOST:
      SMTP_USER:
      SMTP_PASSWORD:
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_ACCESS_TOKEN_KEY:
      TWITTER_ACCESS_TOKEN_SECRET:
      TWITTER_ACCOUNT_NAME:
      NCBI_EUTILS_API_KEY:
  grounding:
    image: pathwaycommons/grounding-search:${GROUNDING_SEARCH_IMAGE_TAG:-latest}
    container_name: grounding_container
    ports:
      - "${GROUNDING_PORT:-3011}:3000"
    depends_on:
      - index
    environment:
      ELASTICSEARCH_HOST: "index:9200"
  indexer:
    image: pathwaycommons/grounding-search:${GROUNDING_SEARCH_IMAGE_TAG:-latest}
    container_name: indexer_container
    depends_on:
      - index
    environment:
      ELASTICSEARCH_HOST: "index:9200"
    command: ["./wait-for-elasticsearch.sh", "index:9200", "npm", "run", "update"]
  index:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: index_container
    volumes:
      - indata:/usr/share/elasticsearch/data
  db:
    image: pathwaycommons/rethinkdb-docker:${RETHINKDB_IMAGE_TAG:-latest}
    container_name: db_container
    ports:
      - "${DB_ADMIN_PORT:-8080}:8080"
    volumes:
      - dbdata:/data
  indra:
    image: indra_intn_server:latest
    container_name: indra_container
    ports:
      - "${INDRA_PORT:-3030}:8000"

volumes:
  dbdata:
    name: dbdata
  indata:
    name: indata