version: "3.8"
services:
  proxy:
    image: nginx:${NGINX_IMAGE_TAG:-latest}
    restart: on-failure
    container_name: proxy_container
    depends_on:
      - webapp
    ports:
      - "${PROXY_PORT:-80}:${NGINX_PORT:-80}"
    volumes:
      - ./templates:/etc/nginx/templates
      - appdata:/var/www/app:ro
    environment:
      NGINX_PORT: "80"
      NGINX_HOST:
      NGINX_PROXY_SERVER: "webapp:3000"
      STATIC_ROOT: /var/www/app/build
      IMAGE_ROOT: /var/www/app/src/styles
  webapp:
    image: pathwaycommons/factoid:${FACTOID_IMAGE_TAG:-latest}
    restart: on-failure
    container_name: webapp_container
    depends_on:
      - db
      - grounding
      - converter
    ports:
      - "${FACTOID_PORT:-3000}:3000"
    volumes:
      - appdata:/home/appuser/app
    environment:
      BASE_URL:
      GROUNDING_SEARCH_BASE_URL: "http://grounding:3000"
      BIOPAX_CONVERTER_URL: "http://converter:8080/convert/v2/"
      SEMANTIC_SEARCH_BASE_URL:
      DB_HOST: "db"
      API_KEY:
      EMAIL_ENABLED:
      SMTP_HOST:
      SMTP_USER:
      SMTP_PASSWORD:
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_ACCESS_TOKEN_KEY:
      TWITTER_ACCESS_TOKEN_SECRET:
      TWITTER_ACCOUNT_NAME:
      NCBI_EUTILS_API_KEY:
      NODE_OPTIONS:
      EMAIL_RELPPRS_CONTACT:
      CRON_SCHEDULE:
  grounding:
    image: pathwaycommons/grounding-search:${GROUNDING_SEARCH_IMAGE_TAG:-latest}
    restart: on-failure
    container_name: grounding_container
    ports:
      - "${GROUNDING_PORT:-3011}:3000"
    depends_on:
      - index
    environment:
      ELASTICSEARCH_HOST: "index:9200"
      NCBI_EUTILS_API_KEY:
      ZENODO_ACCESS_TOKEN:
      ZENODO_BASE_URL:
      ZENODO_BUCKET_ID:
    command: ["./wait-for-elasticsearch.sh", "index:9200", "npm", "run", "boot"]
  index:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    restart: on-failure
    container_name: index_container
    volumes:
      - indata:/usr/share/elasticsearch/data
  db:
    image: pathwaycommons/rethinkdb-docker:${RETHINKDB_IMAGE_TAG:-latest}
    restart: on-failure
    container_name: db_container
    ports:
      - "${DB_ADMIN_PORT:-8080}:8080"
    volumes:
      - dbdata:/data
  converter:
    image: pathwaycommons/factoid-converters:${FACTOID_CONVERTERS_IMAGE_TAG:-latest}
    restart: on-failure
    container_name: converters_container
    ports:
      - "${CONVERTER_PORT:-3082}:8080"

volumes:
  appdata:
    name: appdata
  dbdata:
    name: dbdata
  indata:
    name: indata