// the document controller (used to modify a currently-loaded document)

// functions that are exposed to the client side
module.exports = function( model ){

  /* doc schema:

    document: {
      elements: [
        {
          id: "ent1", // ids are actually just unique junk strings generated by derby
          type: "entity", // indicates the type of entity
          name: "some entity" // user specified name
        },

        {
          id: "int1",
          type: "interaction",
          name: "some interaction",
          participantIds: [ "ent1", "ent2" ] // what participants are connected
        }
      ]
    }
  */

  function isFunction( obj ){
    return typeof obj === "function";
  }

  function isObject( obj ){
    return typeof obj === 'object';
  }

  return {

    // .addInteraction({ [type], [name] })
    // adds an interaction to the doc
    // NB: you should listen via addEntity (not addInteraction)
    // otherwise, you'd have to negotiate and merge multiple events (pretty hard)
    addInteraction: function( interaction ){
      interaction = interaction || {}; // ensure we have an object

      if( interaction.type !== "interaction" ){ // enforce interaction type
        interaction.type = "interaction";
      }

      if( !interaction.name ){
        interaction.name = "new interaction";
      }

      interaction.participantIds = [];
      interaction.interaction = true;

      return this.addEntity(interaction);
    },

    // .addEntity({ [type], [name], [viewport] })
    // add an entity to the document
    // 
    // .addEntity( function( entity ){} )
    // listen for when entities are added
    addEntity: function( entity ){
      var fn = arguments[0];
      if( isFunction( fn ) ){ // then bind to when an entity is added to the doc
        model.on('push', '_entities', function(entity, index, isLocal){
          fn( entity );
        });
        return;

      } else { // then add the entity to the doc
        if( !entity ){ // in case nothing specified
          entity = {};
        }

        if( !entity.type ){ // in case type is elided
          entity.type = "entity";
        }

        if( !entity.name ){ // in case name is elided, use some default value
          entity.name = "new entity";
        }

        entity.entity = true;

        if( !entity.viewport ){
          entity.viewport = {
            x: 0,
            y: 0
          };
        }

        if( entity.id === undefined ){ // then generate an id for the entity
          entity.id = model.id();
        }

        var entityWithSameIdAlreadyExists = this.entity(entity.id) !== undefined;
        if( entityWithSameIdAlreadyExists ){
          return; // there can only be one
        }

        model.push( "_entities", entity );
      }

      return entity;
    },

    // .removeEntity( entityId )
    // removes the entity from the document
    //
    // .removeEntity( function( entityId ){} )
    // listens for when entities are removed
    removeEntity: function( entityId ){
      var fn = arguments[0];
      if( isFunction( fn ) ){ // then bind to when an entity is removed from the doc
        model.on('remove', '_entities', function(index, howMany, removedArray, isLocal){
          for( var i = 0; i < removedArray.length; i++ ){
            var removedEnt = removedArray[i];
            var id = removedEnt.id;

            fn(id);
          }
        });
        return;

      } else { // then remove the entity from the doc
        var index = model.at('_entityIdToIndex').get( entityId );
        model.remove('_entities', index);

        var connectedInts = model.filter('_entities').where('participantIds').contains( [entityId] ).get();
        for( var i = 0; i < connectedInts.length; i++ ){
          var inter = connectedInts[i];

          var pids = inter.participantIds;
          for( var j = 0; j < pids.length; j++ ){
            var pid = pids[j];

            if( pid === entityId ){
              model.remove('_entities.' + i + '.participantIds', j);
            }
          }
        }
      }
    },

    removeAllEntities: function(){
      var length = model.get('_entities.length');
      model.remove('_entities', 0, length);
    },

    // .connectEntityToInteraction(intId, entId) : connects entity to interaction
    // fails when
    //  - entity and interaction are the same
    //  - entity or interaction aren't in the document
    //  - entity is already connected to interaction
    //  - the interaction specified isn't actually one
    //
    // .connectEntityToInteraction()
    connectEntityToInteraction: function( entityId, interactionId ){
      var intIndex, entIndex, interaction, entity;
      var fn = arguments[0];

      if( isFunction(fn) ){ // then listen to when entities are connected to interactions
        model.on('push', '_entities.*.participantIds', function(intIndex, entityId){
          var interactionId = model.get('_entities.' + intIndex + '.id');
          fn(entityId, interactionId);
        });
        return;
      }

      if( interactionId === entityId ){
        return; // you can't connect an interaction to itself
      }

      var entityExists = this.entityExists( entityId );
      var interactionExists = this.entityExists( interactionId );

      var inDoc = entityExists && interactionExists;
      if( !inDoc ){
        return; // you can't connect them together if they don't exist in the doc
      }
      var interaction = this.entity( interactionId );
      var interactionIsRightType = interaction.interaction;
      if( !interactionIsRightType ){ return; } // can't connect if not right type

      // check if the entity is already connected
      var entityAlreadyConnected = this.interactionHasParticipant( interactionId, entityId );
      if( entityAlreadyConnected ){ return; } // can't connect if already connected

      var intIndex = model.get('_entityIdToIndex.' + interactionId);
      model.push('_entities.' + intIndex + '.participantIds', entityId);

    },

    disconnectEntityFromInteraction: function( entityId, interactionId ){
      var fn = arguments[0];

      if( isFunction(fn) ){ // then listen to when entities are disconnected to interactions
        model.on('remove', '_entities.*.participantIds', function(intIndex, index, howMany, removedArray, isLocal){
          var interactionId = model.get('_entities.' + intIndex + '.id');
          for( var i = 0; i < removedArray.length; i++ ){
            var entityId = removedArray[i];

            fn(entityId, interactionId);
          }         
          
        });
        return;
      }

      var entity = this.entity(entityId);
      var interaction = this.entity(interactionId);
      var intIndex = model.get('_entityIdToIndex.' + interactionId);

      var inDoc = entity && interaction;
      var interactionIsRightType = interaction.type === 'interaction;'
      if( !inDoc ){
        return; // you can't connect them together if they don't exist in the doc
      }

      // check if the entity is already connected
      var entityAlreadyConnected = false;
      var pids = interaction.participantIds;
      var entIndex;
      for( var i = 0; i < pids.length; i++ ){
        var pid = pids[i];

        if( pid === entityId ){
          entityAlreadyConnected = true;
          entIndex = i;
          break;
        }
      }

      if( entityAlreadyConnected ){
        model.remove('_entities.' + intIndex + '.participantIds', entIndex, 1);
      }
    },

    // TODO document
    entityName: function( entityId, name ){
      var fn = arguments[0];
    
      if( isFunction(fn) ){
        model.on('set', '_entities.*.name', function(index, newName, oldName, isLocal){
          var entityId = model.get('_entities.' + index + '.id');
          fn( entityId, newName );
        });

      } else if( name === undefined ) {
        var index = model.get('_entityIdToIndex.' + entityId);
        return model.get('_entities.' + index + '.name');

      } else {
        var index = model.get('_entityIdToIndex.' + entityId);
        model.set('_entities.' + index + '.name', name);
      }
    },

    entityViewport: function( entityId, viewport ){
      var fn = arguments[0];

      if( isFunction(fn) ){
        model.on('set', '_entities.*.viewport', function(index, newPos, oldPos, isLocal){

          if( isLocal ){ return; } // don't trigger if we moved it (since we're already up-to-date)

          if( newPos.x === undefined || newPos.y === undefined ){
            return; // can't really do anything :(
          }

          var id = model.get('_entities.' + index + '.id');
          fn(id, newPos);
        });

      } else if( viewport === undefined ) {
        var index = model.get('_entityIdToIndex.' + entityId);
        return model.get('_entities.' + index + '.viewport');
      
      } else {
        var index = model.get('_entityIdToIndex.' + entityId);
        model.set('_entities.' + index + '.viewport', viewport);
      }
    },

    entity: function( entityId ){
      var index = model.get('_entityIdToIndex.' + entityId);
      return model.get('_entities.' + index);
    },

    entityExists: function( entityId ){
      return this.entity( entityId ) !== undefined;
    },

    entities: function(){
      return model.get('_entities');
    },

    interactionParticipants: function( interactionId ){
      var index = model.get('_entityIdToIndex.' + interactionId);
      return model.get('_populatedEntities.' + index + '.participants');
    },

    interactionHasParticipant: function( interactionId, participantId ){
      var intIndex = model.get('_entityIdToIndex.' + interactionId);
      var partsIds = model.get('_entities.' + intIndex + '.participantIds');
      for( var i = 0; i < partsIds.length; i++ ){
        var id = partsIds[i];

        if( id === participantId ){
          return true;
        }
      }

      return false;
    },

    associateEntity: function( entityId, db, dbId, name ){
      var index = model.get('_entityIdToIndex.' + entityId);
      model.set('_entities.' + index + '.' + db, dbId);

      if( name ){
        doc.entityName( entityId, name );
      }
    },

    setTextminingText: function(text, next){
      model.set('_textminingText', text);

      textmining.getPotentialEntitiesFromText(text, function(err, ents){
        doc.setTextminingEntities( ents );
        next();
      });
    },

    setTextminingEntities: function( entities ){
      if( entities ){
        for( var i = 0; i < entities.length; i++ ){
          var ent = entities[i];

          ent.id = model.id();
        }

         model.set('_textminingEntities', entities);
      }
     
    },

    removeAllTextminingEntities: function(){
      model.del('_textminingEntities');
    },

    removeTextminingEntity: function( entityId ){
      var entities = model.get('_textminingEntities') || [];
      for( var i = 0; i < entities.length; i++ ){
        var ent = entities[i];

        if( ent.id === entityId ){
          model.remove('_textminingEntities', i);
          return;
        }
      }
    },

    addCurrentTextminingEntities: function( posFn ){
      var entities = model.get('_textminingEntities') || [];
      model.set('_textminingEntities', []);
      model.set('_textminingText');

      for( var i = 0; i < entities.length; i++ ){
        var ent = entities[i];

        if( posFn ){ // if specified, use the position function to place the entity
          ent.viewport = posFn();
        }

        doc.addEntity( ent );
      }
    }

  };
};