version: "3.8"
services: 
  graphdb:
    image: neo4j:${GRAPHDB_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: graphdb
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - graphdb-data:/data
      - graphdb-plugins:/plugins
    environment:
      NEO4J_AUTH: none
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_PLUGINS: '["apoc"]'
    networks:
      - graphdb-config-network